---
title: "Plots"
author: "Jimmy, A. Warren"
date: "2020/12/3"
output: html_document
---
```{r load-packages}
library(tidyverse)
library(tidymodels)
```

```{r load-data}
teams_cleaned <- read_csv("/cloud/project/data/teams-cleaned.csv")

set.seed(3)
teams_split <- initial_split(teams_cleaned, prop = 0.80)
teams_train <- training(teams_split)
teams_test <- testing(teams_split)
```


```{r batting-average}
#Had to make a bunch of adjustments to Jimmy's plots and add some more stuff for
#analysis purposes. It's the same process for every variable, so I'll just walk
#through the first one.

#create graph, add linear model trendline
teams_train %>%
  ggplot(mapping = aes(x = mean_avg , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

#linear model, note R squared and adjusted R squared
avg_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_avg, data = teams_train)
tidy(avg_fit)
glance(avg_fit)

#residuals analysis
avg_aug <- augment(avg_fit$fit)
ggplot(data = avg_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r slugging-percentage}
teams_train %>%
  ggplot(mapping = aes(x = mean_slg , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

slg_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_slg, data = teams_train)
tidy(slg_fit)
glance(slg_fit)

slg_aug <- augment(slg_fit$fit)
ggplot(data = slg_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r isolated-power}
teams_train %>%
  ggplot(mapping = aes(x = mean_iso , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

iso_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_slg, data = teams_train)
tidy(iso_fit)
glance(iso_fit)

iso_aug <- augment(iso_fit$fit)
ggplot(data = iso_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r batting-average-on-balls-in-play}
teams_train %>%
  ggplot(mapping = aes(x = mean_babip , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

babip_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_babip, data = teams_train)
tidy(babip_fit)
glance(babip_fit)

babip_aug <- augment(babip_fit$fit)
ggplot(data = babip_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r on-base-percentage}
teams_train %>%
  ggplot(mapping = aes(x = mean_obp , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

obp_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_obp, data = teams_train)
tidy(obp_fit)
glance(obp_fit)

obp_aug <- augment(obp_fit$fit)
ggplot(data = obp_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r weighted-on-base-average}
teams_train %>%
  ggplot(mapping = aes(x = mean_w_oba , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

woba_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_w_oba, data = teams_train)
tidy(woba_fit)
glance(woba_fit)

woba_aug <- augment(woba_fit$fit)
ggplot(data = woba_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r weighted-runs-created}
teams_train %>%
  ggplot(mapping = aes(x = mean_w_rc , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

wrc_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_w_rc, data = teams_train)
tidy(wrc_fit)
glance(wrc_fit)

wrc_aug <- augment(wrc_fit$fit)
ggplot(data = wrc_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r base-runs}
teams_train %>%
  ggplot(mapping = aes(x = mean_bsr , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

bsr_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_bsr, data = teams_train)
tidy(bsr_fit)
glance(bsr_fit)

bsr_aug <- augment(bsr_fit$fit)
ggplot(data = bsr_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

```{r offense}
teams_train %>%
  ggplot(mapping = aes(x = mean_off , y = win_rate)) +
  geom_point(size = 1.2, alpha = 0.35) +
  geom_smooth(method = "lm")

off_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(win_rate ~ mean_off, data = teams_train)
tidy(off_fit)
glance(off_fit)

off_aug <- augment(off_fit$fit)
ggplot(data = off_aug,
       aes(x = .fitted,
           y = .resid)) +
  geom_jitter() +
  geom_hline(yintercept = 0,
             linetype = "dashed")
```

